### PR TITLE
Hide BeginNode/EndNode and use a finer-grained coloring scheme for effect nodes

### PR DESCRIPTION
**Pull request by eregon**
`examples/ruby/example_instance_of.bgv:5`:
Before:
old
After:
new

---

`examples/ruby/example_while_break.bgv:5`:
Before:
old
After:
new

---

`examples/graalvm-ce-java11-21.2.0/fib-ruby.bgv.gz:3`:
Before:
old
After:
new

---

"Empty if":
Before:
old
After:
new

### CODE REVIEW

**Comment by eregon** [comment]
I added svg graphs to compare before/after.

**Comment by chrisseaton** [comment]
Leave them in unless they're very simple.

**Review by chrisseaton — APPROVED** [review]

**Comment by eregon** [comment]
> Not convinced about this purple but I'll merge it for now.

Feel free to tweak. I think I'll take anything except red for memory accesses, because red is already used for control flow and control flow is completely unrelated to memory accesses.

**Comment by chrisseaton** [comment]
> control flow is completely unrelated to memory accesses

Both are usually fixed, that's why.

**Pull request merged**
